/* autogenerated by Processing revision 1277 on 2021-10-15 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class BlackholePainting extends PApplet {

Particles[] particles; 

PImage blackhole;
 public void setup() {
  /* size commented out by preprocessor */;
  blackhole = loadImage("blackhole.jpg");
  blackhole.resize(width,height);

  particles = new Particles [1000];
  for (int i = 0; i < particles.length; i++) {
    particles[i] = new Particles();
  }
  background(0);
}

 public void draw() {

  for (int i = 0; i < particles.length; i++) {
    particles[i].display();
    particles[i].move();
  }
}
class Particles {
  float x;
  float y;
  
  float velX;
  float velY;

  Particles() {
    x = width/2;  //sets the particles to start moving in the center
    y = height/2;
    float a = random(TWO_PI);
    float speed = random(1,2);
    velX = cos(a)*speed;
    velY = sin(a)*speed;
  }

   public void display() {
    noStroke();
    int c = blackhole.get(PApplet.parseInt(x),PApplet.parseInt(y)); //pulls the colors 
    fill(c,10);
    ellipse(x, y, 12, 12);
  }

   public void move() {
    x = x + velX;//random(-5, 5);
    y = y + velY;//random(-5, 5);
    if (y < 0) {
      y = height;
    } 

    if (y > height) {
      y = 0;
    }
    if (x < 0) {
      x = width;
    } 

    if (x > width) {
      x = 0;
    }
  }
}


  public void settings() { size(858, 536); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "BlackholePainting" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
